# Site settings
title: SMC Spring 22 Projects 
email: smc-cs@sonoma.edu
url: https://smc.cs.sonoma.edu/S22
description: "Spring 2022 SMC student projects."
keywords: "your keywords, separated by commas"
skills: "Sonoma Mountain Connection - Biology - Computer Science"
meta_author: Sonoma Mountain Connection

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7ABC57
  primary-rgb: "122,188,87"
  secondary: 326027
  secondary-dark: 535554

# Footer settings
footer:
  copyright: Dr. Mark Gondree
  location: Sonoma State University
  social: Website
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: globe
    url: https://scitech.sonoma.edu/college-beyond/sonoma-mountain-connection

# Postal address (add as many lines as necessary)
address:
  - line: 1801 East Cotati Ave
  - line: Rohnert Park, CA 94928

# Credits content
credits: 'Built using <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a>, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
